---
output: github_document

---

```{r setup, include=FALSE}
setwd("/Users/nm572/OneDrive - University of Exeter/Documents/SGG/Projects/bGWAS/")
knitr::opts_chunk$set(echo = TRUE,
                      fig.path = "doc/Figures/README-",
                      out.width = "100%")
# for tibbles...
options(pillar.neg=F, # do no print neg number in red
        pillar.subtle=F, # turn off highliting of significant digits
        tibble.width = 170) # default=95, increase it to make it readable
# A = readRDS("inst/Data/A.RDS")
# # automatically updates manual
# devtools::build_manual()
# system("mv ../bGWAS_1.0.2.pdf doc/bGWAS-manual.pdf")
# #
# remove.packages("bGWAS")
```


```{r badges, echo = FALSE, results='asis'}
# # https://shields.io/
# 
# 
# #TRAVIS CI buil
# cat(
# badger::badge_travis("n-mounier/bGWAS"),
# 
# #version
# #badger::badge_github_version("n-mounier/bGWAS", "informational")
# badger::badge_custom("version", suppressMessages(badger::ver_devel("n-mounier/bGWAS")), "informational", "https://github.com/n-mounier/bGWAS"),
# 
# #lifecycle
# badger::badge_lifecycle("maturing", "9cf"), 
# 
# #last commit:
# badger::badge_last_commit("n-mounier/bGWAS"),
# 
# #license
# badger::badge_custom("license", "GPL-2.0", "lightgrey", "https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html")
# 
# #DOI
# #badger::badge_custom("poster", "10.5281/zenodo.3403093", "blueviolet", "https://doi.org/10.5281/zenodo.3403093")
#)

```



:information\_source: this is a modified version of `bGWAS` meant to be used for the GEMINI project.    


## Contact
<mounier.ninon@gmail.com>

    
      
